import  {mount as productMount} from 'products/ProductsIndex';
import {mount as cartMount} from 'cart/CartSummary';
const hostProducts = document.createElement('div');
hostProducts.classList.add('host-products');
document.body.appendChild(hostProducts);
const hostCart= document.createElement('div');
hostProducts.classList.add('host-cart');
document.body.appendChild(hostCart);
cartMount(hostCart);
console.log('container');
